name: Deploy via SFTP

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Sync Files via SFTP
        uses: pressidium/lftp-mirror-action@v1
        with:
          host: ${{ secrets.SFTP_HOST }}
          port: ${{ secrets.SFTP_PORT }}
          user: ${{ secrets.SFTP_USERNAME }}
          pass: ${{ secrets.SFTP_PASSWORD }}
          # Uploads your specific folder to the matching path on the server
          localDir: "./world/customnpcs/scripts/ecmascript"
          remoteDir: "/world/customnpcs/scripts/ecmascript"
          options: "--exclude .git/"   
